. "$PSScriptRoot\common.ps1"

Write-Host "`n=== Kira Windows 安装包构建脚本 ===" -ForegroundColor Green

try {
    Push-Location (Join-Path $PSScriptRoot '..')

    # 读取版本号
    $pubspec = Get-Content 'pubspec.yaml' -Raw
    if ($pubspec -match '(?m)^version:\s*(\S+)') {
        $version = $Matches[1].Split('+')[0]
    } else {
        throw '无法从 pubspec.yaml 解析版本号'
    }
    Write-Host "版本号: v$version" -ForegroundColor Yellow

    # 检查 .env
    if (-not (Test-Path '.env')) {
        throw '缺少 .env 文件'
    }

    # 检查 ISCC
    $iscc = Get-Command iscc.exe -ErrorAction SilentlyContinue
    if (-not $iscc) {
        throw '找不到 ISCC.exe，请将 Inno Setup 安装目录加入 PATH 后重试'
    }
    Write-Host "ISCC: $($iscc.Source)" -ForegroundColor Yellow

    # 检测 ChineseSimplified.isl 是否存在（Inno Setup 6 默认不带）
    $isccDir = Split-Path $iscc.Source -Parent
    $zhIslPath = Join-Path $isccDir 'Languages\ChineseSimplified.isl'
    $hasChinese = Test-Path $zhIslPath
    if (-not $hasChinese) {
        Write-Host "提示: 未找到 ChineseSimplified.isl，将仅使用英文界面" -ForegroundColor DarkYellow
        Write-Host "      如需中文界面，请下载 https://jrsoftware.org/files/istrans/ChineseSimplified.isl" -ForegroundColor DarkYellow
        Write-Host "      放到 $isccDir\Languages\" -ForegroundColor DarkYellow
    }

    # 构建 Windows release
    # 应用图标由 flutter_launcher_icons 维护 (改图标后请执行: dart run flutter_launcher_icons)
    $icoPath = 'windows\runner\resources\app_icon.ico'
    Write-Host "`n正在构建 Windows release..." -ForegroundColor Yellow
    & flutter build windows `
        --release `
        --dart-define-from-file=.env
    if ($LASTEXITCODE -ne 0) {
        throw "flutter build windows 失败 (exit code: $LASTEXITCODE)"
    }

    $releaseDir = 'build\windows\x64\runner\Release'
    if (-not (Test-Path (Join-Path $releaseDir 'kira.exe'))) {
        throw "未找到构建产物: $releaseDir\kira.exe"
    }
    $releaseFullPath = (Resolve-Path $releaseDir).Path

    # 准备输出目录
    $outputDir = Join-Path (Get-Location) 'build\windows\installer'
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
    }
    $outputBaseName = "kira-v$version-windows-x64-setup"

    # 生成 .iss 文件
    $issPath = Join-Path $outputDir 'installer.iss'
    $iconLine = ''
    if (Test-Path $icoPath) {
        $iconLine = "SetupIconFile=$((Resolve-Path $icoPath).Path)"
    }

    $languagesSection = if ($hasChinese) {
        @'
[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"
'@
    } else {
        @'
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
'@
    }

    $issContent = @"
; Auto-generated by scripts/build_windows.ps1 — do not edit by hand.
#define MyAppName "Kira"
#define MyAppVersion "$version"
#define MyAppPublisher "caolib"
#define MyAppExeName "kira.exe"

[Setup]
AppId={{8C5A1F2E-7E4B-4F3A-9A1D-KIRA-COMIC-READER}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
OutputDir=$outputDir
OutputBaseFilename=$outputBaseName
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
$iconLine

$languagesSection

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenuicon"; Description: "在开始菜单创建快捷方式"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "$releaseFullPath\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: startmenuicon
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; Tasks: startmenuicon
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DocsDir: string;
  ComicDir: string;
  AnimeDir: string;
begin
  if CurUninstallStep = usPostUninstall then begin
    if MsgBox('是否同时删除用户数据？' + #13#10 + #13#10 +
              '将删除已下载的漫画与动漫:' + #13#10 +
              '  - %USERPROFILE%\Documents\comic_downloads' + #13#10 +
              '  - %USERPROFILE%\Documents\anime_downloads' + #13#10 + #13#10 +
              '选择"否"可保留这些数据。',
              mbConfirmation, MB_YESNO or MB_DEFBUTTON1) = IDYES then begin
      DocsDir := ExpandConstant('{userdocs}');
      ComicDir := DocsDir + '\comic_downloads';
      AnimeDir := DocsDir + '\anime_downloads';
      if DirExists(ComicDir) then DelTree(ComicDir, True, True, True);
      if DirExists(AnimeDir) then DelTree(AnimeDir, True, True, True);
    end;
  end;
end;
"@

    Set-Content -Path $issPath -Value $issContent -Encoding UTF8
    Write-Host "已生成: $issPath" -ForegroundColor Green

    # 调用 ISCC 编译
    Write-Host "`n正在编译安装包..." -ForegroundColor Yellow
    & $iscc.Source $issPath
    if ($LASTEXITCODE -ne 0) {
        throw "ISCC 编译失败 (exit code: $LASTEXITCODE)"
    }

    $setupFile = Join-Path $outputDir "$outputBaseName.exe"
    if (-not (Test-Path $setupFile)) {
        throw "未找到安装包产物: $setupFile"
    }

    $fullPath = (Resolve-Path $setupFile).Path
    Write-Host "`n构建产物: $fullPath" -ForegroundColor Green
    Start-Process explorer.exe -ArgumentList "/select,`"$fullPath`""
}
catch {
    Write-Host "错误: $_" -ForegroundColor Red
    exit 1
}
finally {
    Pop-Location
}
